export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


export const ROUTE_ACTIONS = 'ROUTE_ACTIONS';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_DENIED = 'AUTHENTICATE_DENIED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_DENIED = 'LOGOUT_DENIED';

export const LOAD_ACTION_ITEMS_REQUEST = 'LOAD_ACTION_ITEMS_REQUEST';
export const LOAD_ACTION_ITEMS_SUCCESS = 'LOAD_ACTION_ITEMS_SUCCESS';
export const CREATE_ACTION_ITEM_REQUEST = 'CREATE_ACTION_ITEM_REQUEST';
export const CREATE_ACTION_ITEM_SUCCESS = 'CREATE_ACTION_ITEM_SUCCESS';
export const UPDATE_ACTION_ITEM_REQUEST = 'UPDATE_ACTION_ITEM_REQUEST';
export const UPDATE_ACTION_ITEM_SUCCESS = 'UPDATE_ACTION_ITEM_SUCCESS';
export const DELETE_ACTION_ITEM_REQUEST = 'DELETE_ACTION_ITEM_REQUEST';
export const DELETE_ACTION_ITEM_SUCCESS = 'DELETE_ACTION_ITEM_SUCCESS';
